AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for storing user conversation history'

Resources:
  UserConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversation_id
          AttributeType: S
      KeySchema:
        - AttributeName: conversation_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiry_time
        Enabled: true
      Tags:
        - Key: Application
          Value: ContinuumAssistant
        - Key: Component
          Value: ConversationStorage

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref UserConversationsTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt UserConversationsTable.Arn