from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
import re
import io
from datetime import datetime

class EnhancedPDFGenerator:
    def __init__(self):
        self.primary_blue = colors.Color(0.1, 0.2, 0.4)
        self.accent_blue = colors.Color(0.2, 0.4, 0.7)
        self.light_gray = colors.Color(0.95, 0.95, 0.95)
        self.dark_gray = colors.Color(0.3, 0.3, 0.3)
    
    def create_enhanced_pdf(self, content, title="Professional Report"):
        """Generate enhanced PDF with tables, charts, and modern styling"""
        try:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(
                buffer, pagesize=A4,
                topMargin=1*inch, bottomMargin=1*inch,
                leftMargin=1*inch, rightMargin=1*inch
            )
            
            story = []
            
            # Professional header with proper spacing
            story.append(Paragraph(title, self.get_title_style()))
            story.append(Spacer(1, 10))
            story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p UTC')}", 
                                 self.get_subtitle_style()))
            
            # Header separator line
            separator_table = Table([['']], colWidths=[6*inch], rowHeights=[0.1*inch])
            separator_table.setStyle(TableStyle([
                ('LINEBELOW', (0, 0), (-1, -1), 3, self.accent_blue),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0)
            ]))
            
            story.append(separator_table)
            story.append(Spacer(1, 25))
            
            # Executive summary table
            summary_table = self.create_summary_table(content)
            if summary_table:
                story.append(Paragraph("<b>Executive Summary</b>", self.get_heading_style()))
                story.append(summary_table)
                story.append(Spacer(1, 20))
            
            # Price chart for financial content
            if any(word in content.lower() for word in ['bitcoin', 'crypto', 'price', '$']):
                chart = self.create_price_chart(content)
                if chart:
                    story.append(Paragraph("<b>Market Overview</b>", self.get_heading_style()))
                    story.append(chart)
                    story.append(Spacer(1, 20))
            
            # Process content
            self.process_content(content, story)
            
            # Professional footer
            story.append(Spacer(1, 30))
            
            footer_line = Table([['']], colWidths=[6*inch], rowHeights=[0.05*inch])
            footer_line.setStyle(TableStyle([
                ('LINEABOVE', (0, 0), (-1, -1), 1, self.light_gray)
            ]))
            story.append(footer_line)
            
            story.append(Spacer(1, 10))
            story.append(Paragraph("Generated by Son of Anton AI Assistant | Professional Business Intelligence", 
                                 ParagraphStyle('Footer', fontSize=9, textColor=self.dark_gray, 
                                              fontName='Helvetica', alignment=1)))
            
            doc.build(story)
            buffer.seek(0)
            return buffer.getvalue()
            
        except Exception as e:
            print(f"Enhanced PDF error: {str(e)}")
            return None
    
    def get_title_style(self):
        return ParagraphStyle(
            'EnterpriseTitle',
            fontSize=22, spaceAfter=8, spaceBefore=0,
            textColor=self.primary_blue,
            fontName='Helvetica-Bold', alignment=0,
            leftIndent=0
        )
    
    def get_subtitle_style(self):
        return ParagraphStyle(
            'EnterpriseSubtitle',
            fontSize=10, spaceAfter=0, spaceBefore=0,
            textColor=self.dark_gray,
            fontName='Helvetica', alignment=0,
            leftIndent=0
        )
    
    def get_heading_style(self):
        return ParagraphStyle(
            'EnterpriseHeading',
            fontSize=14, spaceAfter=8, spaceBefore=0,
            textColor=self.accent_blue, fontName='Helvetica-Bold',
            borderWidth=0, borderPadding=0,
            leftIndent=0
        )
    
    def get_body_style(self):
        return ParagraphStyle(
            'ModernBody',
            fontSize=11, spaceAfter=10, leading=15,
            fontName='Helvetica', alignment=4,
            leftIndent=0, rightIndent=0
        )
    
    def get_bullet_style(self):
        return ParagraphStyle(
            'ProfessionalBullet',
            fontSize=11, spaceAfter=8, leading=15,
            fontName='Helvetica', alignment=0,
            leftIndent=20, bulletIndent=5,
            textColor=colors.black
        )
    
    def create_summary_table(self, content):
        """Create executive summary table"""
        try:
            metrics = []
            
            # Extract financial metrics
            prices = re.findall(r'\$([0-9,]+\.?\d*)', content)
            if prices:
                metrics.append(['Current Price', f'${prices[0]}'])
            
            percentages = re.findall(r'([+-]?\d+\.?\d*)%', content)
            if percentages:
                metrics.append(['24h Change', f'{percentages[0]}%'])
            
            # Market cap
            market_caps = re.findall(r'market cap[^$]*\$([0-9,]+\.?\d*\s*(?:billion|million|B|M))', content, re.IGNORECASE)
            if market_caps:
                metrics.append(['Market Cap', f'${market_caps[0]}'])
            
            if not metrics:
                return None
            
            table = Table([['Metric', 'Value']] + metrics, colWidths=[2*inch, 2*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), self.primary_blue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('PADDING', (0, 0), (-1, -1), 12),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.8, 0.8, 0.8)),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.97, 0.97, 0.97)])
            ]))
            
            return table
            
        except:
            return None
    
    def create_price_chart(self, content):
        """Create price comparison chart"""
        try:
            prices = re.findall(r'\$([0-9,]+\.?\d*)', content)
            if len(prices) < 2:
                return None
            
            values = [float(p.replace(',', '')) for p in prices[:4]]
            labels = ['BTC', 'ETH', 'APE', 'Other'][:len(values)]
            
            drawing = Drawing(400, 200)
            chart = VerticalBarChart()
            chart.x = 50
            chart.y = 50
            chart.height = 125
            chart.width = 300
            chart.data = [values]
            chart.categoryAxis.categoryNames = labels
            chart.valueAxis.valueMin = 0
            chart.valueAxis.valueMax = max(values) * 1.1
            chart.bars[0].fillColor = self.accent_blue
            chart.categoryAxis.labels.fontSize = 9
            chart.valueAxis.labels.fontSize = 9
            
            drawing.add(chart)
            return drawing
            
        except:
            return None
    
    def process_content(self, content, story):
        """Process content with enhanced formatting"""
        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 8))
                continue
            
            # Headings
            if (line.startswith('##') or line.startswith('**') and line.endswith('**') or
                line.isupper() and len(line) > 5):
                clean_heading = line.strip('#*').strip()
                story.append(Spacer(1, 8))
                story.append(Paragraph(clean_heading, self.get_heading_style()))
                story.append(Spacer(1, 12))
            
            # Data tables
            elif ':' in line and any(char.isdigit() for char in line):
                table = self.create_data_table(line)
                if table:
                    story.append(table)
                    story.append(Spacer(1, 10))
                else:
                    story.append(Paragraph(line, self.get_body_style()))
            
            # Professional bullet points
            elif line.startswith(('- ', '• ', '* ')):
                bullet_text = line.lstrip('- •*').strip()
                story.append(Paragraph(f"▪ {bullet_text}", self.get_bullet_style()))
            
            # Regular paragraphs
            else:
                story.append(Paragraph(line, self.get_body_style()))
    
    def create_data_table(self, text):
        """Create data table from key-value pairs"""
        try:
            pairs = re.findall(r'([^:]+):\s*([^,\n]+)', text)
            if not pairs or len(pairs) < 2:
                return None
            
            data = [[key.strip(), value.strip()] for key, value in pairs[:6]]
            
            table = Table(data, colWidths=[2.5*inch, 2.5*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.Color(0.92, 0.92, 0.92)),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('PADDING', (0, 0), (-1, -1), 10),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.7, 0.7, 0.7)),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.98, 0.98, 0.98)])
            ]))
            
            return table
            
        except:
            return None

# Global instance
enhanced_pdf = EnhancedPDFGenerator()

def create_enhanced_pdf_report(content, title="Professional Report"):
    """Create enhanced PDF with modern styling and data visualization"""
    return enhanced_pdf.create_enhanced_pdf(content, title)